# Activation du gestionnaire d'authentification et configuration du hachage des mots de passe
security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Configuration du fournisseur d'utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Configuration des pare-feu pour contrôler l'accès aux différentes parties de l'application
    firewalls:
        # Pare-feu de développement, permet l'accès aux ressources de développement
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        # Pare-feu principal, gère l'authentification des utilisateurs
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator:
                - App\Security\LoginAuthenticator
            logout:
                path: app_logout

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # Durée de la session de rappel en secondes (7 jours)
                path: /
                always_remember_me: true
                # Redirection après la déconnexion
                # target: app_any_route

            # Activer différentes méthodes d'authentification
            # switch_user: true

    # Configuration des règles d'accès pour les différentes parties de l'application
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

# Configuration spécifique pour les tests
when@test:
    security:
        password_hashers:
            # Configuration pour les tests
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Coût le plus bas possible pour bcrypt
                time_cost: 3 # Coût le plus bas possible pour argon
                memory_cost: 10 # Coût le plus bas possible pour argon
